const RECORD_TIME_IN_MIL_SECONDS = 3600000
const BASE_PATH = '/mnt/alice_nas'
const FROM_EMAIL = '';
const ADDRESSES = '';

module.exports = { RECORD_TIME_IN_MIL_SECONDS, BASE_PATH, FROM_EMAIL, ADDRESSES }